import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <meta name="viewport" content="width=device-width, minimum-scale=1.0"></meta>
      <meta name="theme-color" content="#ea9a38"></meta>
      <body
        className={`${inter.className} bg-port-yellow-ultra-light`}
      >
        {children}
      </body>
    </html>
  );
}
